# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Github/FPGA-course/zynq7020-image-processing/sobel_05_pc_control_display/sobel_05_pc_control_display.srcs/sources_1/bd/ps_uart_bram_hdmi/ip/ps_uart_bram_hdmi_axi_bram_ctrl_0_0/ps_uart_bram_hdmi_axi_bram_ctrl_0_0.xci
# IP: The module: 'ps_uart_bram_hdmi_axi_bram_ctrl_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Github/FPGA-course/zynq7020-image-processing/sobel_05_pc_control_display/sobel_05_pc_control_display.srcs/sources_1/bd/ps_uart_bram_hdmi/ip/ps_uart_bram_hdmi_axi_bram_ctrl_0_0/ps_uart_bram_hdmi_axi_bram_ctrl_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_uart_bram_hdmi_axi_bram_ctrl_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/Github/FPGA-course/zynq7020-image-processing/sobel_05_pc_control_display/sobel_05_pc_control_display.srcs/sources_1/bd/ps_uart_bram_hdmi/ip/ps_uart_bram_hdmi_axi_bram_ctrl_0_0/ps_uart_bram_hdmi_axi_bram_ctrl_0_0.xci
# IP: The module: 'ps_uart_bram_hdmi_axi_bram_ctrl_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Github/FPGA-course/zynq7020-image-processing/sobel_05_pc_control_display/sobel_05_pc_control_display.srcs/sources_1/bd/ps_uart_bram_hdmi/ip/ps_uart_bram_hdmi_axi_bram_ctrl_0_0/ps_uart_bram_hdmi_axi_bram_ctrl_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_uart_bram_hdmi_axi_bram_ctrl_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
