# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Github/FPGA-course/sobel/sobel_04_uart_sobel_hdmi/sobel_04_uart_sobel_hdmi.srcs/sources_1/ip/rgb2dvi_0/rgb2dvi_0.xci
# IP: The module: 'rgb2dvi_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Github/FPGA-course/sobel/sobel_04_uart_sobel_hdmi/sobel_04_uart_sobel_hdmi.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgb2dvi_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Github/FPGA-course/sobel/sobel_04_uart_sobel_hdmi/sobel_04_uart_sobel_hdmi.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgb2dvi_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Github/FPGA-course/sobel/sobel_04_uart_sobel_hdmi/sobel_04_uart_sobel_hdmi.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgb2dvi_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/Github/FPGA-course/sobel/sobel_04_uart_sobel_hdmi/sobel_04_uart_sobel_hdmi.srcs/sources_1/ip/rgb2dvi_0/rgb2dvi_0.xci
# IP: The module: 'rgb2dvi_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Github/FPGA-course/sobel/sobel_04_uart_sobel_hdmi/sobel_04_uart_sobel_hdmi.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgb2dvi_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Github/FPGA-course/sobel/sobel_04_uart_sobel_hdmi/sobel_04_uart_sobel_hdmi.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgb2dvi_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Github/FPGA-course/sobel/sobel_04_uart_sobel_hdmi/sobel_04_uart_sobel_hdmi.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgb2dvi_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
