# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z020clg400-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Github/FPGA-course/sobel/sobel_02_hdmi_sobel/sobel_02_hdmi_sobel.cache/wt [current_project]
set_property parent.project_path D:/Github/FPGA-course/sobel/sobel_02_hdmi_sobel/sobel_02_hdmi_sobel.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths d:/Github/FPGA-course/sobel/exp05_hdmi_out_test/repo [current_project]
set_property ip_output_repo d:/Github/FPGA-course/sobel/sobel_02_hdmi_sobel/sobel_02_hdmi_sobel.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/Github/FPGA-course/sobel/sobel_02_hdmi_sobel/sobel_02_hdmi_sobel.srcs/sources_1/new/rgb_to_gray.v
  D:/Github/FPGA-course/sobel/sobel_02_hdmi_sobel/sobel_02_hdmi_sobel.srcs/sources_1/new/sobel_core.v
  D:/Github/FPGA-course/sobel/sobel_02_hdmi_sobel/sobel_02_hdmi_sobel.srcs/sources_1/new/top.v
}
read_ip -quiet D:/Github/FPGA-course/sobel/sobel_02_hdmi_sobel/sobel_02_hdmi_sobel.srcs/sources_1/ip/rgb2dvi_0/rgb2dvi_0.xci
set_property used_in_implementation false [get_files -all d:/Github/FPGA-course/sobel/sobel_02_hdmi_sobel/sobel_02_hdmi_sobel.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi.xdc]
set_property used_in_implementation false [get_files -all d:/Github/FPGA-course/sobel/sobel_02_hdmi_sobel/sobel_02_hdmi_sobel.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Github/FPGA-course/sobel/sobel_02_hdmi_sobel/sobel_02_hdmi_sobel.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi_clocks.xdc]

read_ip -quiet D:/Github/FPGA-course/sobel/sobel_02_hdmi_sobel/sobel_02_hdmi_sobel.srcs/sources_1/ip/video_clock/video_clock.xci
set_property used_in_implementation false [get_files -all d:/Github/FPGA-course/sobel/sobel_02_hdmi_sobel/sobel_02_hdmi_sobel.srcs/sources_1/ip/video_clock/video_clock_board.xdc]
set_property used_in_implementation false [get_files -all d:/Github/FPGA-course/sobel/sobel_02_hdmi_sobel/sobel_02_hdmi_sobel.srcs/sources_1/ip/video_clock/video_clock.xdc]
set_property used_in_implementation false [get_files -all d:/Github/FPGA-course/sobel/sobel_02_hdmi_sobel/sobel_02_hdmi_sobel.srcs/sources_1/ip/video_clock/video_clock_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Github/FPGA-course/sobel/sobel_02_hdmi_sobel/sobel_02_hdmi_sobel.srcs/constrs_1/new/hdmi_out_test.xdc
set_property used_in_implementation false [get_files D:/Github/FPGA-course/sobel/sobel_02_hdmi_sobel/sobel_02_hdmi_sobel.srcs/constrs_1/new/hdmi_out_test.xdc]


synth_design -top top -part xc7z020clg400-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
