# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/hdmi_out_test.xdc

# IP: ip/video_clock/video_clock.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==video_clock || ORIG_REF_NAME==video_clock} -quiet] -quiet

# Block Designs: bd/ps_uart_bram_hdmi/ps_uart_bram_hdmi.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_uart_bram_hdmi || ORIG_REF_NAME==ps_uart_bram_hdmi} -quiet] -quiet

# IP: bd/ps_uart_bram_hdmi/ip/ps_uart_bram_hdmi_processing_system7_0_0/ps_uart_bram_hdmi_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_uart_bram_hdmi_processing_system7_0_0 || ORIG_REF_NAME==ps_uart_bram_hdmi_processing_system7_0_0} -quiet] -quiet

# IP: bd/ps_uart_bram_hdmi/ip/ps_uart_bram_hdmi_rst_ps7_0_50M_0/ps_uart_bram_hdmi_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_uart_bram_hdmi_rst_ps7_0_50M_0 || ORIG_REF_NAME==ps_uart_bram_hdmi_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/ps_uart_bram_hdmi/ip/ps_uart_bram_hdmi_axi_smc_0/ps_uart_bram_hdmi_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_uart_bram_hdmi_axi_smc_0 || ORIG_REF_NAME==ps_uart_bram_hdmi_axi_smc_0} -quiet] -quiet

# IP: bd/ps_uart_bram_hdmi/ip/ps_uart_bram_hdmi_axi_bram_ctrl_0_0/ps_uart_bram_hdmi_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_uart_bram_hdmi_axi_bram_ctrl_0_0 || ORIG_REF_NAME==ps_uart_bram_hdmi_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/ps_uart_bram_hdmi/ip/ps_uart_bram_hdmi_blk_mem_gen_0_0/ps_uart_bram_hdmi_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_uart_bram_hdmi_blk_mem_gen_0_0 || ORIG_REF_NAME==ps_uart_bram_hdmi_blk_mem_gen_0_0} -quiet] -quiet

# XDC: ip/video_clock/video_clock_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==video_clock || ORIG_REF_NAME==video_clock} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/video_clock/video_clock.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==video_clock || ORIG_REF_NAME==video_clock} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/video_clock/video_clock_ooc.xdc

# XDC: bd/ps_uart_bram_hdmi/ps_uart_bram_hdmi_ooc.xdc
